apiVersion: v1
kind: ConfigMap
metadata:
  name: metrictemplate
data:
  metrictemplate: |
    accountName: opsmx-prom
    metricType: ADVANCED
    advancedProvider: PROMETHEUS
    metricTemplateSetup:
      groups:
        - group: "Performance Score"
          metrics:
            - name: "avg(container_memory_usage_bytes{namespace=\"${namespace_key}\", pod=~\"${pod_key}\"})"
              riskDirection: higher
              customThresholdHigherPercentage: 50
            - name: "avg(rate(container_cpu_usage_seconds_total{namespace=\"${namespace_key}\", pod=~\"${pod_key}\"}[2m]) * 100)"
              riskDirection: higher
              customThresholdHigherPercentage: 50
            - name: "sum(rate(http_server_requests_seconds_sum{app=\"${app_name}\",kubernetes_pod_name=~\"${pod_key}\"}[2m])) / sum(rate(http_server_requests_seconds_count{app=\"${app_name}\",kubernetes_pod_name=~\"${pod_key}\"}[2m]))"
              riskDirection: higher
              customThresholdHigherPercentage: 50
            - name: "avg(rate(http_server_requests_seconds_count{app=\"${app_name}\",kubernetes_pod_name=~\"${pod_key}\"}[2m]))"
              riskDirection: higherOrLower
              customThresholdHigherPercentage: 50
              customThresholdLowerPercentage: 50
            - name: "sum(rate(http_server_requests_seconds_count{app=\"${app_name}\",kubernetes_pod_name=~\"${pod_key}\",status=~\"^[4-5].*\"}[2m])) or vector(0)"
              riskDirection: higher 
              customThresholdHigherPercentage: 50
        - group: "Quality Score"	
          metrics:
            - name: "avg(container_memory_usage_bytes{namespace=\"${namespace_key}\", pod=~\"${pod_key}\"})"
              riskDirection: higher
              customThresholdHigherPercentage: 50
            - name: "avg(rate(container_cpu_usage_seconds_total{namespace=\"${namespace_key}\", pod=~\"${pod_key}\"}[2m]) * 100)"
              riskDirection: higher
              customThresholdHigherPercentage: 50
            - name: "histogram_quantile(0.95,sum by (le) (rate(http_server_requests_seconds_bucket{app=\"${app_name}\",kubernetes_pod_name=~\"${pod_key}\"}[2m])))"
              riskDirection: higher
              customThresholdHigherPercentage: 50
            - name: "histogram_quantile(0.5,sum by (le) (rate(http_server_requests_seconds_bucket{app=\"${app_name}\",kubernetes_pod_name=~\"${pod_key}\"}[2m])))"
              riskDirection: higher
              customThresholdHigherPercentage: 50
            - name: "avg(container_fs_reads_bytes_total{namespace=\"${namespace_key}\",pod=~\"${pod_key}\",container!=\"\"})"
              riskDirection: higherOrLower
              customThresholdHigherPercentage: 50
              customThresholdLowerPercentage: 50
            - name: "avg(container_fs_writes_bytes_total{namespace=\"${namespace_key}\",pod=~\"${pod_key}\",container!=\"\"})"
              riskDirection: higherOrLower
              customThresholdHigherPercentage: 50
              customThresholdLowerPercentage: 50
            - name: "sum(rate(http_server_requests_seconds_count{app=\"${app_name}\",kubernetes_pod_name=~\"${pod_key}\",status=~\"^[5].*\"}[2m])) or vector(0)"
              riskDirection: higher
              customThresholdHigherPercentage: 50
            - name: "sum(rate(http_server_requests_seconds_count{app=\"${app_name}\",kubernetes_pod_name=~\"${pod_key}\",status=~\"^[4].*\"}[2m])) or vector(0)"
              riskDirection: higher
              customThresholdHigherPercentage: 50
        - group: "Reliability Score"
          metrics:
            - name: "sum(rate(http_server_requests_seconds_count{app=\"${app_name}\",kubernetes_pod_name=~\"${pod_key}\",status=~\"^[4-5].*\"}[2m])) or vector(0)"
              riskDirection: higher
              customThresholdHigherPercentage: 50
            - name: "sum(kube_pod_status_phase{phase=\"Failed\",namespace=\"${namespace_key}\",pod=~\"${pod_key}\"})"
              riskDirection: higher
              customThresholdHigherPercentage: 50
