apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: opsmx-newrel-tmpl
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: opsmx-newrel-tmpl
      initialDelay: 30s
      provider:
        job:
          spec:
            backoffLimit: 2
            template:
              spec:
                serviceAccountName: job-acc2
                containers:
                - name: opsmx-analysis
                  image: 'quay.io/opsmxpublic/argo-isd-metric-provider-job:v1.2.1'  
                  imagePullPolicy: Always
                  env:
                    - name: MY_POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: STABLE_POD_HASH
                      value: "{{args.baseline-hash}}"
                    - name: LATEST_POD_HASH
                      value: "{{args.canary-hash}}"
                  volumeMounts:
                    - name: provider-config-volume
                      mountPath: /etc/config/provider
                    - name: verification-config-volume
                      mountPath: /etc/config/templates                      
                    - name: secret-config-volume
                      mountPath: /etc/config/secrets
                      readOnly: true
                restartPolicy: Never
                volumes:
                - name: provider-config-volume
                  configMap:
                    name: opsmx-provider-config
                - name: verification-config-volume
                  projected:
                    sources:
                    - configMap:
                        name: logtemplate
                    - configMap:
                        name: metrictemplate
                - name: secret-config-volume
                  secret:
                    secretName: opsmx-profile
                    optional: false
