apiVersion: batch/v1
kind: Job
metadata:
  name: load-executor-jmeter-job
spec:
  template:
    spec:
      containers:
      - name: isdjob
        command: ["/opt/apache-jmeter-5.5/bin/jmeter.sh", "-n", "-t", "/etc/config/scripts/canary.jmx", "-l", "/tmp/report.out", "-j", "/tmp/tmp.out"]
        image: docker.io/justb4/jmeter:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: jmx-script-volume
          mountPath: /etc/config/scripts
      restartPolicy: Never
      volumes:
      - name: jmx-script-volume
        configMap:
          name: jmx-config-new2
